.TH BLIP.BASH 1
.SH NAME
blip.bash \- Bash Library for Indolent Programmers
.SH SYNOPSIS
source blip.bash
.SH DESCRIPTION
Programmers are lazy. Good system administrators are really lazy. (Why bother doing something more than once)?

Unfortunately, due to the fact that Bash doesn't particularly lend itself to reusable code, it doesn't enjoy the same wealth of shared code available that you find with Python or Perl.

.I "But what about the lazy sysadmin that needs to write a script, where Bash genuinely is the most appropriate option?"
, I hear you ask! Well, by providing functions for many common tasks, I'm hoping that
.B blip
will help fill some of the gaps for those situations.


